### ISSUE TITLE
Missing most of the documentation text.

### ISSUE THREAD

**Issue by sorenwacker** [sphinx-notes/pages#10]
Maybe I need to install sphinxs and other plugins before this works. However, the only thing that gets published is the Readme file, not the sphinx docs.

**Comment by sorenwacker** [comment]
I had to install the theme and the right content is uploaded, however, the css is missing. 

https://lewisresearchgroup.github.io/ms-mint/

**Comment by sorenwacker** [comment]
Does this work together with sphinx-autodocgen ?

**Comment by sorenwacker** [comment]
Apparently a .nojekyll file needs to be present in the gh-pages branch. The stylesheets are working now, however, most of the documentation is not generated. Only the headings are visible.

**Comment by SilverRainZ** [comment]
> Apparently a .nojekyll file needs to be present in the gh-pages branch. The stylesheets are working now, however, most of the documentation is not generated. Only the headings are visible.

The v2 action should add .nojekyll files for you. See https://github.com/sphinx-notes/pages/commit/6c2b466c64756cc97f5f2e4a82e6976c7016483b

**Comment by SilverRainZ** [comment]
> Does this work together with sphinx-autodocgen ?

I think yes, but you should make sure your project is installed:

```
...
WARNING: autodoc: failed to import module 'visualization.plotly.plotly_tools' from module 'ms_mint'; the following exception was raised:
No module named 'ms_mint'
WARNING: autodoc: failed to import module 'visualization.plotly' from module 'ms_mint'; the following exception was raised:
No module named 'ms_mint'
...
```

You can:
-  Install your project by a `docs/requirements.txt` file (and you should change `requirements_path` too)
- Or import your project in `conf.py` like this https://github.com/sphinx-notes/any/blob/master/docs/conf.py#L17

**Comment by sorenwacker** [comment]
It works! Amazing :-) Thank you for your help!
