### ISSUE TITLE
Add support for additional Sphinx options

### ISSUE THREAD

**Issue by haiiliin** [sphinx-notes/pages#14]
When I want to build documentation for different languages, I may use additional Sphinx options like:
```
sphinx-build -b html -D language=zh_CN docs/source docs/build/zh_CN/html
```
Is it possible to pass options like `-D language=zh_CN` to `sphinx-build`, or maybe use the environment variable `SPHINXOPTS`?

**Comment by SilverRainZ** [comment]
Sure, I will add it in recent weeks. PR is also welcome.

**Comment by SilverRainZ** [comment]
Since pages@v3 does not have not this option, reopen it.
