### ISSUE TITLE
Support pyproject.toml for Python requirements

### ISSUE THREAD

**Issue by waltsims** [sphinx-notes/pages#17]
After migrating our project from requirement files to pyproject.toml, out sphinx build has broken.

Current behavior is sphinx-notes pages fails if requirements are in pyproject.toml file.

Feature request would be to:

Add support for pyproject.toml requirements specification.

e.g. ```  pip install '.[docs]'```

**Comment by SilverRainZ** [comment]
Hello waltsims, thanks for your contribution.

I'm not very familiar with poetry so I have a few questions.

- What is the usage `pip install '.[docs]'` called? I can't find it from `pip install --help`.
- is docs a conventional name? Maybe we can make it the default?

**Comment by waltsims** [comment]
Hi @SilverRainZ,

The usage of the `pyproject.toml` file is described extensively in [PEP 621](https://peps.python.org/pep-0621/) and can be found under the key-words dependencies and optional-dependencies.
I don't know if there are any conventions on optional dependency naming so I cannot answer weather or not '.[docs]' should be a default value. I can say though that ```pip install .``` installs the base dependencies, which is why I selected it as the default value for my PR.

I have my k-wave-python project currently successfully using my fork of your repository to build the project docs.
