### ISSUE TITLE
Breaks custom domain setups (removes CNAME file)

### ISSUE THREAD

**Issue by peircej** [sphinx-notes/pages#19]
If a GH repo is set to serve its pages from a custom domain, GH inserts a file into the repo (`CNAME`) but sphinx-notes then consistently deletes that file because of the line here
https://github.com/sphinx-notes/pages/blob/54521400a4021e1c33be0966ae543ce8c8dd1a13/main.sh#L85

which means that it constantly breaks custom domains.

I think we need `rm -vrf * !("CNAME")` here

**Comment by SilverRainZ** [comment]
Previously I kept the CNAME file existing by the sphinx.ext.githubpages extension. Preventing it from removing is a good idea.

**Comment by SilverRainZ** [comment]
Pattern `!("xxx")` seems not work:

```
bash-3.2$ ls
1  2  3  4
bash-3.2$ rm -vrf * !("1")
bash: !: event not found
bash-3.2$ ls
1  2  3  4
```

**Comment by SilverRainZ** [comment]
> rm -vrf * !("1")

I should enable shell ext: `shopt -s extglob`.

**Comment by SilverRainZ** [comment]
This is done in https://github.com/sphinx-notes/pages/pull/13

**Comment by SilverRainZ** [comment]
This fix lands on v3.
