### ISSUE TITLE
Can we pass through an SSH_KEY to enable building private repo pages

### ISSUE THREAD

**Issue by steven-murray** [sphinx-notes/pages#23]
`actions/checkout@v3` accepts a `with: SSH_KEY` argument which needs to be set to grab private repos. Can we accept this key in this repo? Or maybe it would be better to let the user do the checkout, and just use the checked-out repo in this action?

**Comment by SilverRainZ** [comment]
>  it would be better to let the user do the checkout, and just use the checked-out repo in this action?

I think this way is reasonable. I will add an extra option to let the user checkout by self.

**Comment by steven-murray** [comment]
perfect, thanks!

**Comment by SilverRainZ** [comment]
I am busy recently and may not add this feature soon, if you can contribute a PR, I will be very grateful.

**Comment by SilverRainZ** [comment]
See: https://github.com/sphinx-notes/pages#customize-checkout-options

**Comment by steven-murray** [comment]
Thank you!
