### ISSUE TITLE
ls: cannot access '/tmp/sphinx-err*': No such file or directory

### ISSUE THREAD

**Issue by flywire** [sphinx-notes/pages#28]
https://github.com/flywire/tute/actions/runs/4624379652/jobs/8179156788#step:2:258

Wrong path, main folder is repeated.

**Comment by SilverRainZ** [comment]
There are some errors in your workflow, but pages print an unrelated error message (it wants to print the detailed log but can not 
find the correct folder of the error log).

The real error is:

```
 Running Sphinx builder
  Running Sphinx v6.1.3
  
  Configuration error:
  config directory doesn't contain a conf.py file (/home/runner/work/tute/tute/docs)
```

`pages@bugfix/disable-errlog-dumping` disable the detailed log output, you can have a try if necssary.

**Comment by flywire** [comment]
> There are some errors in your workflow

Yes, but I'm not sure what. It would be good if there was a [Minimal Working Example](https://github.com/sphinx-notes/pages/issues/30).
