### ISSUE TITLE
Implement as GitHub Pages

### ISSUE THREAD

**Issue by flywire** [sphinx-notes/pages#30]
If this repository was implemented as GitHub Pages a user could clone the repository, set the publishing sources, and enable actions. User could then modify site as required for their own documentation.

**Comment by flywire** [comment]
Good example: https://github.com/seanzhengw/sphinx-pages/tree/example

**Comment by SilverRainZ** [comment]
I am not sure what you mean, examples are shown on REAMDE.

**Comment by flywire** [comment]
> examples are shown on REAMDE

That is a really crappy way of documenting a documentation site when you could actually use it to demonstrate the framework.

---

https://github.com/squidfunk/mkdocs-material is a documentation site with the code hosted on GitHub and the documentation using the framework as a demonstration in gh-pages. The quickest way for a user to get a nice site is just...

> clone the repository, set the publishing sources, and enable actions. User could then modify site as required for their own documentation.

https://github.com/coderefinery/documentation-example is similar (see https://coderefinery.github.io/documentation/gh_workflow/), it is used to document the site. This repo is actually setup as a template.

**Comment by SilverRainZ** [comment]
Contribute a good example is welcome, IMO I think the existing steps and examples are OK.
