### ISSUE TITLE
Consistency with Sphinx Documentation

### ISSUE THREAD

**Issue by flywire** [sphinx-notes/pages#31]
Should be consistent with https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5. Unfortunately, https://www.sphinx-doc.org/en/master/tutorial/getting-started.html uses a docs/source folder.

**Comment by SilverRainZ** [comment]
~~Sure, supporting separate source directories sounds reasonable.~~

**Comment by SilverRainZ** [comment]
Sorry for the late response, I am not sure what things are inconsistent. If you have a separate source directory, just specify it. 
Beside, the latest `sphinx-quickstart` does not separate the source directory by default:

```
$ sphinx-quickstart
Welcome to the Sphinx 7.2.6 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: <<<<<<<<<<<<<<< N By DEFAULT
```

**Comment by SilverRainZ** [comment]
If you have any question please re-open this.
