### ISSUE TITLE
Incorrect README sphinx version

### ISSUE THREAD

**Issue by t92549** [sphinx-notes/pages#33]
The README states the default sphinx version is 5.3:
https://github.com/sphinx-notes/pages/blob/e208343effcd277d6f2fa2bcf6d3fab5e31152fa/README.rst?plain=1#L100
However, there is no default version, so latest is used:
https://github.com/sphinx-notes/pages/blob/e208343effcd277d6f2fa2bcf6d3fab5e31152fa/action.yml#L25-L28

**Comment by SilverRainZ** [comment]
Thanks for your report!
