### ISSUE TITLE
How to deal with pandoc

### ISSUE THREAD

**Issue by prjemian** [sphinx-notes/pages#40]
... I think we can add a section to README to tell people about "how to install extra dependencies".

_Originally posted by @SilverRainZ in https://github.com/sphinx-notes/pages/issues/24#issuecomment-1455303629_

Not seeing [pandoc in the README](https://github.com/search?q=repo%3Asphinx-notes%2Fpages+pandoc&type=issues) yet.  Indeed, this just fixed my [same problem](https://github.com/prjemian/hklpy2/actions/runs/9010070459).

**Comment by SilverRainZ** [comment]
We already have [this section](https://github.com/sphinx-notes/pages?tab=readme-ov-file#install-extra-dependencies).

Pandoc is one of the possible extra dependencies and nothing special, so I won't mention it. But indeed, adding an example would be better.
