### ISSUE TITLE
Correct usage of the argument documentation_path

### ISSUE THREAD

**Issue by MauroLeidi** [sphinx-notes/pages#45]
Hi, I am trying to use your tools to automatically deploy my sphinx documentation on push, my sphinx documentation to a GitHub pages website. To do so I want to use the documentation_path path, that I thought it should point at the folder containing the .rst files and the conf.py file (./docs/rst/). However the page that is deployed on the website is just the README.md file at the location ./docs/README.md.  Therefore it seems to me that the argument was not used. 

Here is my yml file: https://github.com/MattechLab/monalisa/blob/gh-pages/.github/workflows/deploy.yml

Here the website: https://mattechlab.github.io/monalisa/

Can you help me to understand what am I missing?

**Comment by SilverRainZ** [comment]
Hello, you should not use the branch 'gh-pages' to test your workflow, it will never run, when you push things to this branch, Github automatically runs a Jekyll workflow for you (https://github.com/MattechLab/monalisa/actions/runs/12411608634/job/34649672915), so your README is rendered.

**Comment by MauroLeidi** [comment]
Lovely, thanks.
