### ISSUE TITLE
Pygments version is too old

### ISSUE THREAD

**Issue by astrojuanlu** [sphinx-notes/pages#5]
I was playing with this action and found a super weird error:

https://github.com/astrojl-test/lumache/runs/4251532795?check_suite_focus=true#step:3:186

```
 'HtmlFormatter' object has no attribute 'get_linenos_style_defs'
```

It looks like this method has been a part of pygments `HtmlFormatter` class since 2.7:

https://github.com/pygments/pygments/commit/728fd19ebcb69ddb2c7af159939e1a19ae53a892

However, I see this in the logs:

```
  Requirement already satisfied: Pygments>=2.0 in /usr/lib/python3/dist-packages (from sphinx~=4.2.0; extra == "doc"->lumache==0.1.0->-r /home/runner/work/lumache/lumache/./docs/source/requirements.txt (line 1)) (2.3.1)
```

I'm about to try upgrading it, but I'm anyway not quite sure how that ended up there.

**Comment by astrojuanlu** [comment]
This is a temporary project that might go away, apologies in advance if the links are broken at some point.

**Comment by SilverRainZ** [comment]
It is not issue of this action, and even not issue of Sphinx.

This error is throw by Furo, it requires [pygments ~= 2.7](https://github.com/pradyunsg/furo/blob/main/pyproject.toml#L21) and you should add furo to your requirements.txt.

**Comment by astrojuanlu** [comment]
Furo is getting installed too. I then suspect that the pip version is too old, because it's not solving the dependencies: I see several errors like

```
  ERROR: nbconvert 6.3.0 has requirement pygments>=2.4.1, but you'll have pygments 2.3.1 which is incompatible.
```

**Comment by SilverRainZ** [comment]
>  I then suspect that the pip version is too old

Good point, it is possible bacause pip is installed from system package manager.

I want to known how do you install furo? I can found it in your requirements.txt.

**Comment by astrojuanlu** [comment]
The requirements file has a relative path pointing to this metadata file: 

https://github.com/astrojl-test/lumache/blob/f0b705d799fd9c7740673aa9690637ff5147060c/pyproject.toml#L14

**Comment by SilverRainZ** [comment]
In page@v2, I prefer to used action/setup-python, then we can get a newer pip.

**Comment by SilverRainZ** [comment]
v2 has been published: https://github.com/sphinx-notes/pages/tree/v2

Feel free to reopen this if you still suffer this issue.
