### ISSUE TITLE
Possibly dumb question...

### ISSUE THREAD

**Issue by rpgoldman** [sphinx-notes/pages#7]
When I build the docs for [my project](https://github.com/rpgoldman/pyDcop/) by invoking Sphinx manually, I get a `_build/` directory with a `_static/` subdirectory that contains needed components:

```
$ ls _build/_static/
basic.css                 documentation_options.js  jquery.js                 minus.png                 searchtools.js
css/                      file.png                  js/                       plus.png                  underscore-1.13.1.js
doctools.js               jquery-3.5.1.js           language_data.js          pygments.css              underscore.js
```

But when I generate my page using this GitHub action, that `_static` directory seems to be missing, and the resulting page does not display properly.  See https://rpgoldman.github.io/pyDcop/

This is likely something obvious that I just don't understand: I took over a large project that had been abandoned, and I am afraid I don't understand its internals as well as I should.

I see in the docs for pages under "Tips"  there is the following:

> [](https://sphinx-notes.github.io/pages/#copy-extra-files-to-site)Copy extra files to site

> Use Sphinx confval [html_extra_path](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path).

Unfortunately, the Sphinx documents for this conf value are so terse that this does not help; I can't tell if this is related to my problem.

Thank you for any suggestions.

**Comment by rpgoldman** [comment]
Could this be related --  my `.gitignore` file contains the following:

```
# Sphinx documentation
docs/_build/
```

Could this keep the static materials from being committed to the `gh-pages` branch?

**Comment by rpgoldman** [comment]
I do not believe this can be the problem, because when I  look into the `gh-pages` files, the `_static` directory appears, see https://github.com/rpgoldman/pyDcop/tree/gh-pages/_static

**Comment by SilverRainZ** [comment]
It seems that the action works well, `_static` is correctly installed, but I don't know why we can not access it through github pages. Can you run the action again?

**Comment by SilverRainZ** [comment]
What's you `gh-pages` setting? For example:

![image](https://user-images.githubusercontent.com/8090459/164190164-7a7a2e17-9f4d-4758-ad69-4951cc6c52a8.png)

**Comment by rpgoldman** [comment]
> It seems that the action works well, `_static` is correctly installed, but I don't know why we can not access it through github pages. Can you run the action again?

I just ran the action again, and I see the same poorly-formatted page.

I reloaded using Firefox's development tools and I see the following in the network window, which supports what you say:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/3274/164249947-87060dab-50bf-43b7-987e-59ca94174a06.png">

Is there any way to see what is actually there on GitHub, so I can tell if 

1. those files failed to deploy, or 
2. the files were deployed, but permissions are not correct to serve them?

**Comment by rpgoldman** [comment]
> What's your `gh-pages` setting?

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/3274/164251411-8f98089f-4758-4df5-a6f0-e4769e7d82cc.png">

**Comment by rpgoldman** [comment]
P.S. Thank you very much for helping!

**Comment by SilverRainZ** [comment]
> You should enable extension sphinx.ext.githubpages in your conf.py first.

I think you forget to do this?

**Comment by rpgoldman** [comment]
OK, I am sorry -- I made a mistake in configuration and forgot to push the change with the extension!  Yes, that was the problem!

**Comment by SilverRainZ** [comment]
I pushed a commit to branch v2 for this, the `sphinx.ext.githubpages` extension is no longer needed, so we can use this action without change your sphinx conf.
