### ISSUE TITLE
Become a verified creator on Github Marketplace

### ISSUE THREAD

**Issue by Vinno97** [sphinx-notes/pages#9]
Hi,

My firm recently enacted a policy of blocking GH Actions from unverified sources.
Since this is an action by the official Sphinx-notes organization, I think it only makes sense to make this verified.

From https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges, I read:

> Certain apps on the GitHub Marketplace have the badge and a tooltip that says "Publisher domain and email verified". This means that the app is owned by an organization that has:
> * Verified ownership of their domain and has a verified badge on their profile
> * Confirmed their email address so GitHub Support can reach the organization
> * Required two-factor authentication for their organization. For more information, see "[Requiring two-factor authentication in your organization](https://docs.github.com/en/organizations/keeping-your-organization-secure/requiring-two-factor-authentication-in-your-organization)."

How feasible are these conditions in the organization? I'm not sure about the first condition, but the second and third sound like preferred policies anyways.

Happy to hear your opinions.

**Comment by SilverRainZ** [comment]
Sorry for replying so late, it seems that these three conditions are for Github Apps, not Github actions.

> Actions with the [badge] , or verified creator badge, indicate that GitHub has verified the creator of the action as a partner organization.

I am not sure what is partner organization……

**Comment by SilverRainZ** [comment]
I just let domain and mail verified, 2FA is enabled too, and nothing happens.

**Comment by SilverRainZ** [comment]
No response, close it.
